# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{communigate}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ricardo Hermida Ruiz"]
  s.date = %q{2009-08-26}
  s.email = %q{ricardo.ruiz@locaweb.com.br}
  s.files = [
    "Rakefile",
     "VERSION",
     "lib/communigate/cli.rb",
     "lib/communigate/cli_parser.rb",
     "lib/communigate/data_block.rb",
     "lib/communigate/data_exception.rb",
     "lib/communigate/general_exception.rb",
     "spec/cgp_to_ruby_spec.rb",
     "spec/ruby_to_cgp_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/rhruiz/communigate}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Interact with CommuniGatePro CLI interface}
  s.test_files = [
    "spec/cgp_to_ruby_spec.rb",
     "spec/ruby_to_cgp_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
